<% require "dotenv"; Dotenv.load(".env") %>

service: demo-elixir-phoenix
image: gambala/demo_project
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: phoenix.gambala.pro
  app_port: 4000
  healthcheck:
    interval: 10
    path: /up
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - SECRET_KEY_BASE
    - DATABASE_URL
    - PHX_HOST
accessories:
  db:
    image: postgres:15
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
builder:
  arch: arm64
