service: demo-elixir-phoenix
image: gambala/demo_project
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
labels:
  traefik.http.routers.demo-elixir-phoenix-web.rule: Host(`phoenix.gambala.pro`)
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - SECRET_KEY_BASE
    - DATABASE_URL
    - PHX_HOST
accessories:
  db:
    image: postgres:15
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV["DB_PORT"] %>:5432
    env:
      secret:
        - POSTGRES_DB
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
builder:
  multiarch: false
healthcheck:
  interval: 10s
  path: /up
  port: 4000
traefik:
  args:
    api.dashboard: true
  labels:
    traefik.enable: true
    traefik.http.routers.dashboard.rule: Host(`traefik.gambala.pro`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    traefik.http.routers.dashboard.service: api@internal
